"""3 commit

Revision ID: 0c465a0ee5c2
Revises: d4428e1dd244
Create Date: 2020-05-11 23:15:48.246494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c465a0ee5c2'
down_revision = 'd4428e1dd244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
