"""4 commit

Revision ID: 1d3414f5424a
Revises: 72c798286900
Create Date: 2020-05-12 00:17:12.340501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3414f5424a'
down_revision = '72c798286900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
