"""5 commit

Revision ID: 4c7ca5c7b462
Revises: 1d3414f5424a
Create Date: 2020-05-12 00:18:58.779033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7ca5c7b462'
down_revision = '1d3414f5424a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
