"""8 commit

Revision ID: 504bfff951ed
Revises: a0162f6d6cf2
Create Date: 2020-05-17 16:01:04.609374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504bfff951ed'
down_revision = 'a0162f6d6cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threshold')
    # ### end Alembic commands ###
