"""second commit

Revision ID: 72c798286900
Revises: 0c465a0ee5c2
Create Date: 2020-05-11 23:17:56.828815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c798286900'
down_revision = '0c465a0ee5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
