"""upgrade User

Revision ID: a0162f6d6cf2
Revises: 071bf00239fe
Create Date: 2020-05-13 20:14:29.704852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0162f6d6cf2'
down_revision = '071bf00239fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
