"""second commit

Revision ID: d4428e1dd244
Revises: 79f3d8a5821d
Create Date: 2020-05-11 22:52:16.052108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4428e1dd244'
down_revision = '79f3d8a5821d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
